apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
spec:
  type: NodePort
  selector:
    app: myjavaapp
  ports:
  - port: 8080 #Container Port Number
    nodePort: 30001 #Access Port Number
    protocol: TCP