apiVersion: argoproj.io/vlapha1
kind : Application  
metadata:
  name: myapp-argo-application  
  namespcae: argocd 
spec:
  project: default

  source: 
    repoURL: https://github.com/amitmaurya07/ArgocCD_Practise/tree/main/Argo_CD%20Files
    targetRevision: HEAD 
    path: Argo_CD Files 
  destination:
    server: https://kubernetes.default.svc
    namespcae: myapp 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
    selfHeal: true
    prune: true
