apiVersion: argoproj.io/v1apha1
kind : Application  
metadata:
  name: myapp-argo-application  
  namespace: argocd 
spec:
  project: default

  source: 
    repoURL: https://github.com/amitmaurya07/My_k8S_Pods.git
    targetRevision: HEAD 
    path: Argo_CD Practise 
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
    selfHeal: true
    prune: true
